export const finalDTO = {
  order: 0,
  name: 'Final Name',
  alias: 'Final Alias',
  group_alias: 'Group Alias',
  tcp_port: 1000,
  udp_port: 2000,
  wi_port: 3000,
  wi_password: 'WiPassword',
  max_connections: 10000,
  max_files: 500000,
  downstream_limit: 0,
  user_cache_reloading_interval: 1,
  is_nat: 0,
  proxify_ipv6: 0,
  hidden: 0,
  is_proxy: 0,
  threads: 4,
  password: 'PASSWORD',
  zabbix_hostid: 1,
  datacenter_id: 1,
  logging: 1,
  server_id: 1,
};

export const finals = [
  {
    order: 0,
    name: 'Final Name',
    alias: 'Final Alias',
    group_alias: 'Group Alias',
    tcp_port: 1000,
    udp_port: 2000,
    wi_port: 3000,
    wi_password: 'WiPassword',
    max_connections: 10000,
    max_files: 500000,
    downstream_limit: 0,
    user_cache_reloading_interval: 1,
    is_nat: 0,
    proxify_ipv6: 0,
    hidden: 0,
    is_proxy: 0,
    threads: 4,
    password: 'PASSWORD',
    zabbix_hostid: 1,
    datacenter_id: 1,
    logging: 1,
    server_id: 1,
  },
  {
    order: 0,
    name: 'Final Name 2',
    alias: 'Final Alias 2',
    group_alias: 'Group Alias 2',
    tcp_port: 1000,
    udp_port: 2000,
    wi_port: 3000,
    wi_password: 'WiPassword',
    max_connections: 10000,
    max_files: 500000,
    downstream_limit: 0,
    user_cache_reloading_interval: 1,
    is_nat: 0,
    proxify_ipv6: 0,
    hidden: 0,
    is_proxy: 0,
    threads: 4,
    password: 'PASSWORD',
    zabbix_hostid: 1,
    datacenter_id: 1,
    logging: 1,
    server_id: 1,
  },
];
